language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

#branches:
#  only:
#  - master

cache:
  directories:
    - node_modules

before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - npm run test-headless-coveralls
  - ng build --prod --output-path dist --base-href /OpenApiVisualiser/
  - cp dist/index.html dist/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: dist
  on:
    branch: master