# This is a basic workflow to help you get started with Actions

name: Build, Test and Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  build-test-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout 🛎️
      uses: actions/checkout@v2
      with:
        # Shallow clones should be disabled for a better relevancy of sonar analysis
        fetch-depth: 0
    # This installs node and npm for us
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    # Lint and Build
    - name: Install, Lint and Build 🔧
      run: |
        npm install
        npm run-script lint
        npm run-script build-deployment
    # Run tests
    - name: Test
      run: |
        npm run-script test:all
    # Code quality checks
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        # Needed to get PR information, if any
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    # Deploy to GH pages
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.
        CLEAN: true
