# This is a basic workflow to help you get started with Actions

name: Build, Test and Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  build-test-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout 🛎️
      uses: actions/checkout@v2
    # This installs node and npm for us
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    # this allows for re-using node_modules caching, making builds a bit faster.
    - uses: actions/cache@v1 
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    # Lint and Build
    - name: Install, Lint and Build 🔧
      run: |
        npm install
        npm run-script lint
        npm run-script build-deployment
    # Run tests
    - name: Test
      run: |
        npm run-script test-headless
    # Deploy to GH pages
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.
        CLEAN: true
